include_recipe 'base::packages'
include_recipe 'base::firewall'
include_recipe 'base::ssh'
include_recipe 'base::imds'
include_recipe 'base::sudoers'
include_recipe 'base::fail2ban'
include_recipe 'base::unattended_upgrades'
include_recipe 'base::chrony'
include_recipe 'base::sysctl'
include_recipe 'base::cinc_client'
include_recipe 'base::aws_access'
include_recipe 'base::docker'
include_recipe 'base::traefik'
include_recipe 'base::nvidia_docker'
include_recipe 'base::werf'
include_recipe 'base::kubernetes'
include_recipe 'base::nodejs'
include_recipe 'base::claude_code'
include_recipe 'base::gh'
include_recipe 'base::shell_default'
include_recipe 'base::yq'
include_recipe 'base::uv'
include_recipe 'base::tailscale'
# Before base::alloy, deliberately. base::alloy's dev-vm-loki-token resource is
# documented there as relying on being last: it declares returns [0, 10] so an
# unreachable SSM does not fail the converge, and that note points out the
# placement is incidental rather than guaranteed. Keeping alloy last honours it.
include_recipe 'base::falco'
include_recipe 'base::alloy'
